services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8080:8080'
      - '9090:9090'
    volumes:
      - .:/swoole-app
      - ./vendor:/swoole-app/vendor
    working_dir: /swoole-app
    networks:
      - bridge

networks:
  bridge: